## General Data Cleaning

In [1]:
# load data, libraries
import pandas as pd
import numpy as np

df = pd.read_csv('/content/train_transaction.csv')

# join test and train data

df.head()

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [2]:
# drop V columns that are not useful
Keeping = ['V1', 'V3', 'V4', 'V6', 'V8', 'V11', 'V13', 'V14', 'V17', 'V20', 'V23', 'V26', 'V27', 'V30', 'V36', 'V37', 'V40', 'V41', 'V44', 'V47', 'V48', 'V54', 'V56', 'V59', 'V62', 'V65', 'V67', 'V68', 'V70', 'V76', 'V78', 'V80', 'V82', 'V86', 'V88', 'V89', 'V91', 'V127', 'V98', 'V99', 'V107', 'V108', 'V111', 'V115', 'V117', 'V120', 'V121', 'V123', 'V124', 'V129', 'V130', 'V136', 'V138', 'V139', 'V142', 'V147', 'V156', 'V162', 'V165', 'V160', 'V166', 'V203', 'V176', 'V173', 'V207', 'V205', 'V215', 'V169', 'V171', 'V175', 'V209', 'V185', 'V188', 'V198', 'V210', 'V264', 'V223', 'V267', 'V226', 'V228', 'V240', 'V258', 'V252', 'V260', 'V266', 'V277', 'V220', 'V221', 'V234', 'V238', 'V250', 'V271', 'V307', 'V284', 'V285', 'V286', 'V291', 'V297', 'V303', 'V305', 'V309', 'V310', 'V320', 'V281', 'V283', 'V289', 'V296', 'V301', 'V314', 'V332', 'V325', 'V335']

df_subset = df[Keeping]

df_final = pd.concat([df.loc[:, :'M9'], df_subset], axis=1)

df_final.head()

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,V320,V281,V283,V289,V296,V301,V314,V332,V325,V335
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
identity = pd.read_csv('/content/train_identity.csv')

# if a transactionID is in both datasets, flag it
df_final['hasID'] = df_final['TransactionID'].astype(str).isin( identity['TransactionID'].astype(str)).astype(int)

identity = None

## Dealing with Categorical Values

In [4]:
# create list of categorical values
cat_features = df.select_dtypes(include=['object']).columns
# bucket certain columns into groups
for col in cat_features:
  display(df[col].value_counts())

ProductCD
W    439670
C     68519
R     37699
H     33024
S     11628
Name: count, dtype: int64

card4
visa                384767
mastercard          189217
american express      8328
discover              6651
Name: count, dtype: int64

card6
debit              439938
credit             148986
debit or credit        30
charge card            15
Name: count, dtype: int64

P_emaildomain
gmail.com           228355
yahoo.com           100934
hotmail.com          45250
anonymous.com        36998
aol.com              28289
comcast.net           7888
icloud.com            6267
outlook.com           5096
msn.com               4092
att.net               4033
live.com              3041
sbcglobal.net         2970
verizon.net           2705
ymail.com             2396
bellsouth.net         1909
yahoo.com.mx          1543
me.com                1522
cox.net               1393
optonline.net         1011
charter.net            816
live.com.mx            749
rocketmail.com         664
mail.com               559
earthlink.net          514
gmail                  496
outlook.es             438
mac.com                436
juno.com               322
aim.com                315
hotmail.es             305
roadrunner.com         305
windstream.net         305
hotmail.fr             295
frontier.com           280
embarqmail.com         260
web.de                 240
netzero.com            230
twc.com                230
prodigy.net.mx         207
centurylink.net        205
netzero.net            196
frontiernet.net        195
q.com                  189
suddenlink.net         175
cfl.rr.com             172
sc.rr.com              164
cableone.net           159
gmx.de                 149
yahoo.fr               143
yahoo.es               134
hotmail.co.uk          112
protonmail.com          76
yahoo.de                74
ptd.net                 68
live.fr                 56
yahoo.co.uk             49
hotmail.de              43
servicios-ta.com        35
yahoo.co.jp             32
Name: count, dtype: int64

R_emaildomain
gmail.com           57147
hotmail.com         27509
anonymous.com       20529
yahoo.com           11842
aol.com              3701
outlook.com          2507
comcast.net          1812
yahoo.com.mx         1508
icloud.com           1398
msn.com               852
live.com              762
live.com.mx           754
verizon.net           620
me.com                556
sbcglobal.net         552
cox.net               459
outlook.es            433
att.net               430
bellsouth.net         422
hotmail.fr            293
hotmail.es            292
web.de                237
mac.com               218
prodigy.net.mx        207
ymail.com             207
optonline.net         187
gmx.de                147
yahoo.fr              137
charter.net           127
mail.com              122
hotmail.co.uk         105
gmail                  95
earthlink.net          79
yahoo.de               75
rocketmail.com         69
embarqmail.com         68
scranton.edu           63
yahoo.es               57
live.fr                55
juno.com               53
roadrunner.com         53
frontier.com           52
windstream.net         47
hotmail.de             42
protonmail.com         41
yahoo.co.uk            39
cfl.rr.com             37
aim.com                36
servicios-ta.com       35
yahoo.co.jp            33
twc.com                29
ptd.net                27
cableone.net           27
q.com                  25
suddenlink.net         25
frontiernet.net        14
netzero.com            14
centurylink.net        12
netzero.net             9
sc.rr.com               8
Name: count, dtype: int64

M1
T    319415
F        25
Name: count, dtype: int64

M2
T    285468
F     33972
Name: count, dtype: int64

M3
T    251731
F     67709
Name: count, dtype: int64

M4
M0    196405
M2     59865
M1     52826
Name: count, dtype: int64

M5
F    132491
T    107567
Name: count, dtype: int64

M6
F    227856
T    193324
Name: count, dtype: int64

M7
F    211374
T     32901
Name: count, dtype: int64

M8
F    155251
T     89037
Name: count, dtype: int64

M9
T    205656
F     38632
Name: count, dtype: int64

In [5]:
# make T/F columns binary
t_f = ['M2', 'M1', 'M3', 'M5', 'M6', 'M7', 'M8', 'M9']

for col in t_f:
  df_final.loc[df_final[col] == 'T', col] = 1
  df_final.loc[df_final[col] == 'F', col] = 0
  df_final.loc[df_final[col].isna(), col] = -999 # null imputation
  df_final[col] = df_final[col].astype(int)

df_final[t_f].value_counts()

M2    M1    M3    M5    M6    M7    M8    M9
-999  -999  -999  -999  -999  -999  -999  -999    154875
                         0    -999  -999  -999     26584
                         1    -999  -999  -999     25129
 1     1     1    -999   0     0     0     1       22568
                         1     0     0     1       20244
                                                   ...
             0     0     0     1     1     0           1
                         1     1     0     0           1
                  -999   0    -999   0     1           1
             1    -999   0     1     0     0           1
                   1     1     0     1     0           1
Name: count, Length: 230, dtype: int64

In [8]:
df_final[t_f].head()

    M2   M1   M3   M5   M6   M7   M8   M9
0    1    1    1    0    1 -999 -999 -999
1 -999 -999 -999    1    1 -999 -999 -999
2    1    1    1    0    0    0    0    0
3 -999 -999 -999    1    0 -999 -999 -999
4 -999 -999 -999 -999 -999 -999 -999 -999

In [6]:
# lump debit or credit and charge card into other category
df_final.loc[df['card6'] == 'debit or credit', 'card6'] = 'Other'
df_final.loc[df['card6'] == 'charge card', 'card6'] = 'Other'

df_final['card6'].value_counts()

card6
debit     439938
credit    148986
Other         45
Name: count, dtype: int64

In [7]:
# transform DX columns to be constant for each UID despite delta value
# we can determine what is important during feature selection.
date_col = ['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11','D12','D13','D14','D15']
for col in date_col:
  df_final[col] = df_final['TransactionDT'] - df_final[col]

In [9]:
df_final[['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11','D12','D13','D14','D15']].fillna(-999, inplace=True)

/tmp/ipykernel_20675/712327243.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11','D12','D13','D14','D15']].fillna(-999, inplace=True)

In [10]:
df_final.to_csv('/content/train_transaction_clean.csv')